### PR TITLE
Added the ability to import SVGs as a React Component

### PR DESCRIPTION
**Pull request by SentoxAIO**
Added svgr as a loader for SVGs which allows you to import SVGs as Components.

https://react-svgr.com/docs/webpack/

### CODE REVIEW

**Comment by SentoxAIO** [comment]
Update: Made it using the old url-loader options

**Comment by loopmode** [comment]
Do I understand correctly that with this change, the default behavior does not change for existing projects? And that only if you use the named import explicitly you'll have the new behavior?

**Comment by SentoxAIO** [comment]
@loopmode yeah, the svg can still be imported as a url string, like it was before.

Example:
```
import starUrl, { ReactComponent as Star } from './star.svg'
const App = () => (
  <div>
    <img src={starUrl} alt="star" />
    <Star />
  </div>
)
```

**Review by loopmode — APPROVED** [review]

**Comment by SentoxAIO** [comment]
Do you might know when the next release will come?

**Pull request merged**
