### PR TITLE
Added a `staticSourceDirectory` configuration option

### LINKED ISSUE #194: Missing `staticSourceDirectory` setting
I'd like to have my `static` directory somewhere else.

There's already a setting for moving the `common`, `main` and `renderer` directories, one for the `static` directory is weirdly missing, or I couldn't find it.

### PR DESCRIPTION
**Pull request by fabiospampinato**
Closes #194.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Btw I've been using this in [Notable](https://github.com/fabiospampinato/notable) for the past month or so and I haven't encountered any problems.

**Comment by fabiospampinato** [comment]
@develar can I do anything to get this merged in faster? I'd like to switch back from my fork of electron-webpack to the official version.

**Comment by loopmode** [comment]
@fabiospampinato sorry for the very late reply. Looks good, looks useful and safe. Right now however, there are merge conflicts, possibly because we just merged your other PR.
Please revisit this one if you find the time. We will merge it as soon the conflicts are resolved - please comment then and mention me directly. Thanks!

**Comment by fabiospampinato** [comment]
@loopmode I'll take care of the merge conflicts in a few hours, thanks!

**Comment by fabiospampinato** [comment]
@loopmode conflict resolved 👍

**Pull request merged**
