### PR TITLE
Fix __static in production

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Here, made this changed to make it work in production.

### CODE REVIEW

**Comment by develar** [comment]
I don’t understand. In production your static files located in the resourcesPath, what’s wrong?

**Comment by rodrigopavezi** [comment]
@develar it was not finding under the resource folder for me. I needed to change it to the same as the renderer configs to make it work. It fix this issue here https://github.com/electron-userland/electron-webpack/issues/114. Cheers

**Comment by amaurymartiny** [comment]
Just tried this branch, fixes #157 for me.

**Comment by loopmode** [comment]
@develar still unclear? Seems worth merging..

**Comment by rodrigopavezi** [comment]
@develar It fixed for me because the production app built with electron-builder was running on my laptop where I also have the source code. So it was finding the file because I had the source code folder. It was doing like when running in dev mode.

I will close this PR because it does not make sense.

After doing more tests I end up packaging the static files within the asar. 

I am not sure but first off all the __static is not global so it cannot find it when running production. Then if you try adding global__static = __static in the main.js. It will find __static but will not be able to require the file such as a json file when doing `require(__static + 'assets/data.json')`.

There is still this bug but I don't have time anymore to pursue a fix for that. 

Cheers

**Comment by yovanoc** [comment]
Someone planned to fix this ? :/

**Pull request closed without merging**
